# Generated by Django 5.0.4 on 2024-04-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
